### ISSUE TITLE
Info URLs aren't resolvable

### ISSUE THREAD

**Issue by CloCkWeRX** [planningalerts-scrapers/leeton#1]
http://ehc.leeton.nsw.gov.au/Horizon/logonGuest.aw?e=FxkUAB1eSSgbAR0MXx0SGBFSVh0yBwc3GV0eFxcFSUMAIQYHJARfEBMKEiNZACg9HR0CHCUfHBY1QAQsHRAVAlkcGFUPEUcrNBURWDdAAxoQAhVEHS8aNxUCUVUSGBUrWRB9REJEWAJDR09PRABEcERDRkIeQ0ZITRpVAx8AEhY%3D

... but there's no DNS entries corresponding to that publically available

**Comment by henare** [comment]
:facepalm:
